# Workflow exemple pour AWS

name: CI

on:
  # Permet de lancer la pipeline par action manuelle
  workflow_dispatch:

jobs:
  exemple:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::069987675187:role/wnofl
          aws-region: eu-west-1

      - name: List bucket
        shell: bash        
        run: |
          aws s3 ls
